const questions = [
  // ---------------- PYTHON 1–20 ----------------
  {q:"Python is a ___ language?", o:["Compiled","Interpreted","Markup","Assembly"], a:1},
  {q:"Which is a Python data type?", o:["list","arraylist","vector","queue"], a:0},
  {q:"Which symbol is used for comments in Python?", o:["//","#","/*","<!--"], a:1},
  {q:"Python is ___ typed language?", o:["Strongly","Weakly","Dynamically","Loosely"], a:2},
  {q:"Which function outputs to the screen in Python?", o:["print()","echo()","console()","display()"], a:0},
  {q:"Which of these is immutable?", o:["List","Tuple","Set","Dictionary"], a:1},
  {q:"Python file extension is?", o:[".py",".java",".c",".txt"], a:0},
  {q:"Which operator is for exponent in Python?", o:["^","**","%","//"], a:1},
  {q:"Which keyword is used to define a function?", o:["func","define","def","function"], a:2},
  {q:"How to create an empty set?", o:["{}","[]","set()","()"], a:2},
  {q:"Which loop is used to iterate over a sequence?", o:["for","while","loop","repeat"], a:0},
  {q:"Which method adds an element to a list?", o:["append()","add()","insert()","push()"], a:0},
  {q:"Python supports ___ inheritance", o:["Single","Multiple","Multi-level","All"], a:3},
  {q:"Which is NOT a keyword in Python?", o:["pass","eval","assert","then"], a:3},
  {q:"Python's standard library includes ___?", o:["math","java.util","stdio","iostream"], a:0},
  {q:"Which method removes last element from a list?", o:["pop()","remove()","del()","delete()"], a:0},
  {q:"Which function returns length of a list?", o:["size()","length()","len()","count()"], a:2},
  {q:"Which is used for exception handling?", o:["try-except","catch","handle","error"], a:0},
  {q:"Which of these is mutable?", o:["String","Tuple","List","None"], a:2},
  {q:"Python supports ___ programming?", o:["Procedural","Object-Oriented","Functional","All"], a:3},

  // ---------------- JAVA 21–40 ----------------
  {q:"Java is ___ typed language?", o:["Strongly","Weakly","Dynamically","Loosely"], a:0},
  {q:"Which method is entry point in Java?", o:["main()","start()","run()","init()"], a:0},
  {q:"Which keyword is used to inherit a class?", o:["extends","implements","inherits","super"], a:0},
  {q:"Which of these is a Java primitive type?", o:["int","Integer","String","Object"], a:0},
  {q:"Which operator is used for comparison?", o:["==","=","===","!="], a:0},
  {q:"Which is used for single-line comments?", o:["//","/*","#","--"], a:0},
  {q:"Which keyword is used to define a constant?", o:["final","const","static","immutable"], a:0},
  {q:"Which method is used to print in Java?", o:["System.out.println()","console.log()","print()","echo()"], a:0},
  {q:"Which of these is NOT a Java keyword?", o:["class","method","interface","package"], a:1},
  {q:"Which exception occurs when dividing by zero?", o:["ArithmeticException","IOException","NullPointerException","ClassNotFoundException"], a:0},
  {q:"Which keyword is used to create a new object?", o:["new","create","object","instantiate"], a:0},
  {q:"Which is used for multi-line comments?", o:["/* */","//","<!-- -->","#"], a:0},
  {q:"Which is used to prevent method overriding?", o:["final","static","private","protected"], a:0},
  {q:"Which of these is NOT an access modifier?", o:["public","private","default","global"], a:3},
  {q:"Which method compares two strings?", o:["equals()","compare()","==","match()"], a:0},
  {q:"Which keyword defines an interface?", o:["interface","class","implements","abstract"], a:0},
  {q:"Which package contains Scanner class?", o:["java.util","java.io","java.lang","java.net"], a:0},
  {q:"Which keyword is used to inherit multiple interfaces?", o:["implements","extends","inherit","interface"], a:0},
  {q:"Which of these is NOT a loop in Java?", o:["do-while","for","repeat","while"], a:2},
  {q:"Which operator is used for logical AND?", o:["&&","||","&","and"], a:0},

  // ---------------- AI 41–60 ---------------- (easy)
  {q:"AI stands for?", o:["Artificial Intelligence","Automatic Internet","Artificial Input","None"], a:0},
  {q:"Which algorithm is commonly used for search in AI?", o:["A*","DFS","BFS","Linear Search"], a:0},
  {q:"Machine Learning is a subset of?", o:["AI","Data Science","Python","Networking"], a:0},
  {q:"Which is supervised learning?", o:["Regression","Clustering","PCA","None"], a:0},
  {q:"AI type that mimics human intelligence?", o:["Narrow AI","General AI","Strong AI","Weak AI"], a:1},
  {q:"Neural Network is used for?", o:["Pattern Recognition","Database","Networking","Hardware"], a:0},
  {q:"Which is NOT an AI programming language?", o:["HTML","Python","Java","C++"], a:0},
  {q:"Which algorithm is used for optimization?", o:["Genetic Algorithm","DFS","BFS","QuickSort"], a:0},
  {q:"Chatbots use which AI technique?", o:["NLP","Compiler","Assembly","Circuit"], a:0},
  {q:"Reinforcement learning is based on?", o:["Trial & Error","Regression","Clustering","Decision Tree"], a:0},
  {q:"AI can be classified into ___ types", o:["3","2","5","4"], a:0},
  {q:"Which AI is used in self-driving cars?", o:["Narrow AI","General AI","Expert System","Super AI"], a:0},
  {q:"Which is NOT part of AI?", o:["Python","Expert System","Machine Learning","Sensors"], a:0},
  {q:"Which algorithm searches trees?", o:["Minimax","DFS","QuickSort","Bubble"], a:0},
  {q:"Which method evaluates game moves?", o:["Minimax","Maxflow","Sort","DFS"], a:0},
  {q:"Which AI method is probabilistic?", o:["Bayesian","DFS","Stack","Queue"], a:0},
  {q:"Which algorithm uses heuristics?", o:["A*","DFS","BFS","Bubble"], a:0},
  {q:"Which AI is used in healthcare?", o:["Expert System","Compiler","OS","Router"], a:0},
  {q:"Which algorithm solves puzzles?", o:["A*","DFS","MergeSort","Heap"], a:0},
  {q:"Which AI technique is used in spam filters?", o:["Bayes","DFS","Stack","Queue"], a:0},

  // ---------------- COMPUTER NETWORKS 61–80 ----------------
  {q:"IP stands for?", o:["Internet Protocol","Internal Process","Input Port","None"], a:0},
  {q:"OSI model has how many layers?", o:["5","6","7","8"], a:2},
  {q:"Which layer is responsible for routing?", o:["Network","Transport","Application","Physical"], a:0},
  {q:"Which protocol is connection-oriented?", o:["TCP","UDP","IP","HTTP"], a:0},
  {q:"Which device connects networks?", o:["Router","Switch","Hub","Repeater"], a:0},
  {q:"DNS translates?", o:["Domain to IP","IP to MAC","URL to HTTP","None"], a:0},
  {q:"HTTP stands for?", o:["HyperText Transfer Protocol","HighText Transfer Protocol","Hyper Terminal Protocol","None"], a:0},
  {q:"Which protocol is used for email?", o:["SMTP","FTP","TCP","IP"], a:0},
  {q:"Which is a wireless protocol?", o:["Wi-Fi","TCP","IP","UDP"], a:0},
  {q:"Which port does HTTP use?", o:["80","21","443","25"], a:0},
  {q:"Which layer handles encryption?", o:["Presentation","Session","Transport","Network"], a:0},
  {q:"Which protocol is used for secure web?", o:["HTTPS","HTTP","FTP","SMTP"], a:0},
  {q:"Which device filters packets?", o:["Firewall","Router","Switch","Hub"], a:0},
  {q:"Ping uses which protocol?", o:["ICMP","TCP","UDP","IP"], a:0},
  {q:"Which is NOT a network topology?", o:["Circular","Star","Ring","Bus"], a:0},
  {q:"Which IP version is IPv4?", o:["32-bit","64-bit","128-bit","16-bit"], a:0},
  {q:"Which protocol resolves MAC address?", o:["ARP","RARP","IP","TCP"], a:0},
  {q:"Which is used for file transfer?", o:["FTP","SMTP","DNS","IP"], a:0},
  {q:"Which layer provides logical addressing?", o:["Network","Data Link","Physical","Transport"], a:0},
  {q:"Which is a network security protocol?", o:["SSL","HTML","CSS","JavaScript"], a:0},

  // ---------------- BCA EASY GENERAL KNOWLEDGE 81–100 ----------------
  {q:"Who is known as the Father of Computers?", o:["Charles Babbage","Alan Turing","Steve Jobs","Bill Gates"], a:0},
  {q:"Which language is mainly used for web pages?", o:["HTML","Python","Java","C"], a:0},
  {q:"Which language is used to style web pages?", o:["CSS","JavaScript","Python","Java"], a:0},
  {q:"Which language is used to make web pages interactive?", o:["JavaScript","HTML","C++","Java"], a:0},
  {q:"What does CPU stand for?", o:["Central Processing Unit","Computer Personal Unit","Central Programming Unit","Control Processing Unit"], a:0},
  {q:"Which is an input device?", o:["Keyboard","Monitor","Printer","Speaker"], a:0},
  {q:"Which is an output device?", o:["Monitor","Keyboard","Mouse","Scanner"], a:0},
  {q:"Which of these is an operating system?", o:["Windows","HTML","JavaScript","Python"], a:0},
  {q:"Which storage is temporary?", o:["RAM","Hard Disk","SSD","ROM"], a:0},
  {q:"Which storage is permanent?", o:["Hard Disk","RAM","Cache","Registers"], a:0},
  {q:"Which company developed Windows OS?", o:["Microsoft","Apple","IBM","Google"], a:0},
  {q:"Which language is used for database queries?", o:["SQL","Python","Java","HTML"], a:0},
  {q:"Which of these is a database?", o:["MySQL","Python","C++","Java"], a:0},
  {q:"Which is a common browser?", o:["Chrome","Python","Java","C"], a:0},
  {q:"Which is used to send emails?", o:["SMTP","HTTP","FTP","TCP"], a:0},
  {q:"Which is used to browse the internet?", o:["Browser","IDE","Compiler","Server"], a:0},
  {q:"Which company created Java?", o:["Sun Microsystems","Microsoft","Apple","IBM"], a:0},
  {q:"Which device connects a computer to a network?", o:["Router","Monitor","Keyboard","Mouse"], a:0},
  {q:"Which programming language starts with 'P' and is easy to learn?", o:["Python","Perl","PHP","Pascal"], a:0},
  {q:"Which website is mainly for developers?", o:["Stack Overflow","YouTube","Facebook","Instagram"], a:0},
];
