const allQuestions = {
    bca: [
        { q: "Which programming language is known as the 'mother of all languages'?", o: ["Java", "C", "C++", "Python"], a: 1 },
        { q: "What is the primary function of an Operating System?", o: ["Web browsing", "Hardware management", "Database entry", "Photo editing"], a: 1 },
        { q: "Which data structure follows the 'First In First Out' (FIFO) principle?", o: ["Stack", "Array", "Queue", "Tree"], a: 2 },
        { q: "What does the 'HTTP' prefix in a website address stand for?", o: ["High Text Transfer Protocol", "HyperText Transfer Protocol", "Hyper Transfer Text Process", "Hidden Text Transfer Protocol"], a: 1 },
        { q: "Which of these is a valid IP address?", o: ["192.168.1.1", "256.0.0.1", "172.16.256", "10.0.0.1.1"], a: 0 },
        { q: "What is the purpose of a 'Primary Key' in SQL?", o: ["To lock a table", "To uniquely identify a record", "To encrypt data", "To sort names alphabetically"], a: 1 },
        { q: "In Python, which keyword is used to create a function?", o: ["func", "define", "def", "function"], a: 2 },
        { q: "Which of the following is an example of 'Open Source' software?", o: ["Windows", "Photoshop", "Linux", "Microsoft Office"], a: 2 },
        { q: "What does HTML stand for?", o: ["HyperText Markup Language", "HighText Machine Language", "Hyperlink Text Mod", "Home Tool Markup Language"], a: 0 },
        { q: "Which part of the computer is responsible for mathematical calculations?", o: ["RAM", "CU", "ALU", "Register"], a: 2 },
        { q: "What is the binary representation of decimal 10?", o: ["1010", "1100", "1001", "1111"], a: 0 },
        { q: "Which of these is a 'volatile' memory?", o: ["Hard Drive", "ROM", "RAM", "Flash Drive"], a: 2 },
        { q: "What is the standard port for HTTPS?", o: ["80", "21", "443", "8080"], a: 2 },
        { q: "In OOPs, what is the process of hiding internal details?", o: ["Inheritance", "Polymorphism", "Encapsulation", "Abstractions"], a: 2 },
        { q: "Which protocol is used to transfer files between computers?", o: ["SMTP", "FTP", "HTTP", "SNMP"], a: 1 },
        { q: "A kilobyte is exactly how many bytes?", o: ["1000", "1024", "1048", "1200"], a: 1 },
        { q: "Which gate gives an output of 1 only if all inputs are 1?", o: ["OR", "AND", "NOT", "XOR"], a: 1 },
        { q: "What is the extension of a Java bytecode file?", o: [".java", ".class", ".exe", ".obj"], a: 1 },
        { q: "Which device is used to connect different networks?", o: ["Switch", "Hub", "Router", "Repeater"], a: 2 },
        { q: "What does SQL stand for?", o: ["Simple Query Language", "System Query Language", "Structured Query Language", "Stable Query Logic"], a: 2 },
        { q: "Which CSS property is used to change text color?", o: ["text-style", "font-color", "color", "background-color"], a: 2 },
        { q: "What is the full form of URL?", o: ["Universal Resource Locator", "Uniform Resource Locator", "United Resource Link", "User Response Line"], a: 1 },
        { q: "In C, which function is used to print output?", o: ["echo()", "println()", "printf()", "write()"], a: 2 },
        { q: "Which cloud service model provides a virtual machine?", o: ["SaaS", "PaaS", "IaaS", "DaaS"], a: 2 },
        { q: "What is 'phishing' in cybersecurity?", o: ["A type of coding", "A fraudulent email attack", "Updating software", "A search engine"], a: 1 },
        { q: "Which language is used for styling web pages?", o: ["HTML", "XML", "CSS", "PHP"], a: 2 },
        { q: "What is the base of the Hexadecimal system?", o: ["2", "8", "10", "16"], a: 3 },
        { q: "Which sorting algorithm has an average time complexity of O(n log n)?", o: ["Bubble Sort", "Quick Sort", "Insertion Sort", "Selection Sort"], a: 1 },
        { q: "What is the function of a 'Compiler'?", o: ["Execute program", "Translate high-level to machine code", "Design UI", "Clean memory"], a: 1 },
        { q: "Which tag is used for the largest heading in HTML?", o: ["<head>", "<h6>", "<h1>", "<big>"], a: 2 },
        { q: "Which protocol is used for sending emails?", o: ["SMTP", "POP3", "IMAP", "HTTP"], a: 0 },
        { q: "What is a 'variable' in programming?", o: ["A fixed value", "A storage location with a name", "A type of hardware", "A function"], a: 1 },
        { q: "Which loop is guaranteed to run at least once?", o: ["while", "for", "do-while", "foreach"], a: 2 },
        { q: "What is the brain of the computer?", o: ["Motherboard", "CPU", "RAM", "Hard Disk"], a: 1 },
        { q: "Which layer of the OSI model handles routing?", o: ["Transport", "Network", "Physical", "Data Link"], a: 1 },
        { q: "What is the shortcut to save a file in Windows?", o: ["Ctrl+S", "Alt+S", "Ctrl+V", "Shift+S"], a: 0 },
        { q: "Which database is 'NoSQL'?", o: ["MySQL", "Oracle", "MongoDB", "PostgreSQL"], a: 2 },
        { q: "What does 'WWW' stand for?", o: ["Web Wide World", "World Wide Web", "World Whole Web", "Web Work World"], a: 1 },
        { q: "Which key is used to delete a file permanently?", o: ["Delete", "Shift+Delete", "Alt+Delete", "Ctrl+Delete"], a: 1 },
        { q: "What is a group of 8 bits called?", o: ["Nibble", "Byte", "Word", "Block"], a: 1 },
        { q: "In database terms, what is a 'Row' called?", o: ["Field", "Attribute", "Tuple", "Schema"], a: 2 },
        { q: "Which operator is used for 'Not Equal To' in most languages?", o: ["<>", "==", "!=", "&&"], a: 2 },
        { q: "What is the main purpose of a Firewall?", o: ["Stop computer fires", "Network security", "Faster internet", "File compression"], a: 1 },
        { q: "Which language is used for Artificial Intelligence primarily?", o: ["Fortran", "Pascal", "Python", "Assembly"], a: 2 },
        { q: "What is 'Latency' in networking?", o: ["Data speed", "Network delay", "Total bandwidth", "Packet size"], a: 1 },
        { q: "Which component stores the BIOS settings?", o: ["RAM", "CMOS Battery", "Hard Drive", "CPU Cache"], a: 1 },
        { q: "What is the full form of PDF?", o: ["Portable Document Format", "Printable Digital File", "Private Data File", "Portable Detail Folder"], a: 0 },
        { q: "Which command is used to list files in Linux?", o: ["dir", "ls", "list", "show"], a: 1 },
        { q: "What is the primary role of a 'Web Server'?", o: ["Create websites", "Host and deliver web pages", "Manage local files", "Fix internet"], a: 1 },
        { q: "What is the shortcut to refresh a page?", o: ["F1", "F5", "F10", "Alt+F4"], a: 1 }
    ],
    tamil: [
        { q: "Who is known as the 'Father of Tamil Literature'?", o: ["Kambar", "Agathiyar", "Thiruvalluvar", "Ilango Adigal"], a: 1 },
        { q: "How many letters are in the Tamil Uyir Eluthukkal?", o: ["10", "12", "18", "247"], a: 1 },
        { q: "Thirukkural is divided into how many main sections (Paal)?", o: ["2", "3", "4", "5"], a: 1 },
        { q: "Who wrote the famous line 'Yaathum Oore Yaavarum Kelir'?", o: ["Kaniyan Pungundranar", "Bharathiyar", "Avvaiyar", "Kambar"], a: 0 },
        { q: "Which city is known as the 'Tamil Sangam city'?", o: ["Chennai", "Madurai", "Thanjavur", "Coimbatore"], a: 1 },
        { q: "Who is the author of 'Ponniyin Selvan'?", o: ["Kalki Krishnamurthy", "Sandilyan", "Jayakanthan", "Sujaatha"], a: 0 },
        { q: "Which Tamil king built the Kallanai dam?", o: ["Raja Raja Cholan", "Karikala Cholan", "Pandian Nedunchezhiyan", "Cheran Senguttuvan"], a: 1 },
        { q: "What is the first month of the Tamil calendar?", o: ["Aadi", "Chithirai", "Thai", "Margazhi"], a: 1 },
        { q: "Who wrote 'Panchali Sabatham'?", o: ["Bharathidasan", "Subramania Bharathi", "Kannadasan", "Vaali"], a: 1 },
        { q: "How many Kurals are there in Thirukkural?", o: ["1300", "1330", "1500", "1000"], a: 1 },
        { q: "What is the meaning of 'Agam' in Sangam literature?", o: ["War", "Interior/Love", "Statecraft", "Justice"], a: 1 },
        { q: "Which is the state tree of Tamil Nadu?", o: ["Neem", "Palm Tree", "Banyan", "Mango"], a: 1 },
        { q: "Silappathikaram belongs to which category of literature?", o: ["Ettuthogai", "Pathinen Kilkanakku", "Aimperum Kappiyangal", "Pathupattu"], a: 2 },
        { q: "Who wrote the Tamil National Anthem 'Tamil Thai Valthu'?", o: ["Bharathiyar", "Manonmaniam Sundaranar", "Bharathidasan", "Namakkal Kavignar"], a: 1 },
        { q: "Which flower is the state flower of Tamil Nadu?", o: ["Lotus", "Jasmine", "Gloriosa Lily", "Rose"], a: 2 },
        { q: "The word 'Tamil' literally means what?", o: ["Ancient", "Sweet", "Strong", "First"], a: 1 },
        { q: "Who is called 'Kavichakravarthy'?", o: ["Ottakkoothar", "Kambar", "Pugazhendhi", "Avvaiyar"], a: 1 },
        { q: "Which island is associated with Thiruvalluvar Statue?", o: ["Pamban", "Kanyakumari Rock", "Vypeen", "Havelock"], a: 1 },
        { q: "How many lines does a 'Kural Venpa' have?", o: ["1", "2", "3", "4"], a: 1 },
        { q: "Which is the oldest surviving Tamil grammar book?", o: ["Nannool", "Tholkappiyam", "Agathiyam", "Viracholiyam"], a: 1 },
        { q: "Who is known as 'Puthumaipithan'?", o: ["C. Viruthachalam", "S. Ramakrishnan", "Jeyamohan", "Nanjil Nadan"], a: 0 },
        { q: "What is the secondary name for 'Tamil Language'?", o: ["Amudhu", "Uyir", "Semmozhi", "None"], a: 2 },
        { q: "Which poet is known as 'Paavendhar'?", o: ["Bharathiyar", "Bharathidasan", "Suradha", "Mudiyarasan"], a: 1 },
        { q: "Which king built the Brihadeeswarar Temple?", o: ["Rajendra Chola", "Raja Raja Chola I", "Karikala Chola", "Aditya Chola"], a: 1 },
        { q: "Which epic tells the story of Kannagi?", o: ["Manimekalai", "Silappathikaram", "Civaka Cintamani", "Valayapathi"], a: 1 },
        { q: "How many consonants (Mei Eluthukkal) are in Tamil?", o: ["12", "18", "30", "216"], a: 1 },
        { q: "Who wrote 'Aathichoodi'?", o: ["Bharathiyar", "Avvaiyar", "Kambar", "Thiruvalluvar"], a: 1 },
        { q: "What is the capital of the Pandya Kingdom?", o: ["Kanchipuram", "Madurai", "Poompuhar", "Korkai"], a: 1 },
        { q: "Which instrument is considered the classical instrument of Tamil Nadu?", o: ["Veena", "Nadaswaram", "Flute", "Tabla"], a: 1 },
        { q: "What is the term for 'Friendship' in Tamil literature?", o: ["Anbu", "Natpu", "Paasam", "Kadhal"], a: 1 },
        { q: "Who is the female poet of the Sangam period?", o: ["Andal", "Avvaiyar", "Karaikkal Ammaiyar", "Mangayarkarasi"], a: 1 },
        { q: "Which work is called 'The Bible of Tamil Land'?", o: ["Bible", "Thirukkural", "Ramayanam", "Mahabharatham"], a: 1 },
        { q: "Which bird is the state bird of Tamil Nadu?", o: ["Peacock", "Emerald Dove", "Parrot", "Eagle"], a: 1 },
        { q: "Who is the 'Father of Tamil Cinema'?", o: ["H.M. Reddy", "S.S. Vasan", "M.G.R", "Sivaji Ganesan"], a: 0 },
        { q: "Which dance form originated in Tamil Nadu?", o: ["Kathakali", "Bharatanatyam", "Kuchipudi", "Odissi"], a: 1 },
        { q: "Which town is famous for its silk sarees?", o: ["Salem", "Kanchipuram", "Erode", "Karur"], a: 1 },
        { q: "Who is the first Tamil poet to win a Sahitya Akademi Award?", o: ["Akilan", "Vairamuthu", "Jayakanthan", "Kannadasan"], a: 0 },
        { q: "What is the meaning of 'Puram' in Sangam literature?", o: ["Love", "War/External", "Nature", "God"], a: 1 },
        { q: "Which is the classical language status year for Tamil?", o: ["2000", "2004", "2010", "1995"], a: 1 },
        { q: "How many dots (Ayutha Eluthu) does Tamil have?", o: ["1", "2", "3", "0"], a: 0 },
        { q: "Who translated Thirukkural into Latin?", o: ["G.U. Pope", "Constantius Joseph Beschi", "Ellis", "Drew"], a: 1 },
        { q: "Who translated Thirukkural into English?", o: ["G.U. Pope", "Beschi", "Max Muller", "Warren Hastings"], a: 0 },
        { q: "What is the Tamil name for the month of January/February?", o: ["Thai", "Masi", "Panguni", "Aani"], a: 0 },
        { q: "Which district is 'The Gateway to South India'?", o: ["Chennai", "Madurai", "Trichy", "Tirunelveli"], a: 0 },
        { q: "Which hill station is called the 'Queen of Hill Stations' in TN?", o: ["Kodaikanal", "Ooty", "Yercaud", "Munnar"], a: 1 },
        { q: "Who wrote 'Periya Puranam'?", o: ["Sekkizhar", "Nambiandar Nambi", "Sundarar", "Appar"], a: 0 },
        { q: "What is the traditional martial art of Tamil Nadu?", o: ["Kalaripayattu", "Silambam", "Karate", "Judo"], a: 1 },
        { q: "Which Chola king invaded Sri Lanka?", o: ["Raja Raja I", "Rajendra I", "Kulothunga I", "Aditya I"], a: 0 },
        { q: "The festival of harvest in Tamil Nadu is called?", o: ["Diwali", "Pongal", "Onam", "Vishu"], a: 1 },
        { q: "Which script was used for ancient Tamil inscriptions?", o: ["Grantha", "Tamil Brahmi", "Devanagari", "Arabic"], a: 1 }
    ],
    english: [
        { q: "What is the synonym of 'Abolish'?", o: ["Build", "Destroy", "Cancel", "Support"], a: 2 },
        { q: "What is the antonym of 'Fragile'?", o: ["Weak", "Strong", "Broken", "Soft"], a: 1 },
        { q: "Which word is a noun in: 'The blue bird sang loudly.'", o: ["Blue", "Bird", "Sang", "Loudly"], a: 1 },
        { q: "Choose the correctly spelled word:", o: ["Recieve", "Receive", "Receve", "Reseive"], a: 1 },
        { q: "He is ___ tallest boy in the class.", o: ["a", "an", "the", "none"], a: 2 },
        { q: "Identify the tense: 'I have seen this movie.'", o: ["Past Simple", "Present Perfect", "Past Perfect", "Present Continuous"], a: 1 },
        { q: "What is the plural of 'Child'?", o: ["Childs", "Children", "Childrens", "Childes"], a: 1 },
        { q: "Which of these is a conjunction?", o: ["And", "Quickly", "Happy", "Above"], a: 0 },
        { q: "A person who writes books is an...?", o: ["Artist", "Author", "Actor", "Architect"], a: 1 },
        { q: "Which is an adjective?", o: ["Run", "Slowly", "Beautiful", "Table"], a: 2 },
        { q: "The past tense of 'Eat' is...?", o: ["Eaten", "Ate", "Eats", "Eating"], a: 1 },
        { q: "What is the meaning of 'Incredible'?", o: ["Not believable", "Very small", "Normal", "False"], a: 0 },
        { q: "She ___ to the market yesterday.", o: ["go", "goes", "went", "going"], a: 2 },
        { q: "What is a synonym for 'Huge'?", o: ["Gigantic", "Tiny", "Mean", "Rough"], a: 0 },
        { q: "Identify the preposition: 'The cat is under the table.'", o: ["Cat", "Is", "Under", "Table"], a: 2 },
        { q: "Choose the correct article: 'I saw ___ elephant.'", o: ["a", "an", "the", "none"], a: 1 },
        { q: "What is the opposite of 'Wealthy'?", o: ["Rich", "Poor", "Greedy", "Strong"], a: 1 },
        { q: "Which word means 'a collection of stars'?", o: ["Galaxy", "Universe", "Planet", "Comet"], a: 0 },
        { q: "Choose the correct verb: 'The dogs ___ barking.'", o: ["is", "am", "are", "was"], a: 2 },
        { q: "What does the idiom 'Piece of cake' mean?", o: ["Difficult task", "Easy task", "Delicious food", "A birthday party"], a: 1 },
        { q: "Which sentence is correct?", o: ["She don't like appls.", "She doesn't likes apples.", "She doesn't like apples.", "She not like apples."], a: 2 },
        { q: "What is the comparative form of 'Good'?", o: ["Gooder", "Best", "Better", "Well"], a: 2 },
        { q: "Identify the adverb: 'He ran fast.'", o: ["He", "Ran", "Fast", "None"], a: 2 },
        { q: "What is the prefix in the word 'Unhappy'?", o: ["Un", "Happy", "Hap", "Py"], a: 0 },
        { q: "What is the suffix in the word 'Carefully'?", o: ["Care", "Full", "Ly", "Fully"], a: 2 },
        { q: "A place where planes take off and land is an...?", o: ["Station", "Port", "Airport", "Garage"], a: 2 },
        { q: "What is a group of lions called?", o: ["Pack", "Herd", "Pride", "Flock"], a: 2 },
        { q: "Which word is a pronoun?", o: ["John", "He", "City", "Run"], a: 1 },
        { q: "What is the antonym of 'Optimist'?", o: ["Hopeful", "Pessimist", "Leader", "Winner"], a: 1 },
        { q: "A person who studies space is an...?", o: ["Astrologist", "Astronomer", "Astronaut", "Scientist"], a: 1 },
        { q: "Which word is spelled correctly?", o: ["Necessary", "Necesary", "Neccessary", "Nesesary"], a: 0 },
        { q: "What is the synonym of 'Start'?", o: ["Finish", "Begin", "End", "Stop"], a: 1 },
        { q: "I have been living here ___ 2010.", o: ["for", "since", "from", "at"], a: 1 },
        { q: "The book is ___ the bag.", o: ["on", "in", "at", "to"], a: 1 },
        { q: "What is the feminine of 'King'?", o: ["Prince", "Princess", "Queen", "Maid"], a: 2 },
        { q: "Choose the plural of 'Knife':", o: ["Knifes", "Knives", "Knive", "Knivies"], a: 1 },
        { q: "Identify the interjection: 'Wow! That was amazing.'", o: ["Wow", "That", "Amazing", "Was"], a: 0 },
        { q: "What is the homophone for 'Hear'?", o: ["Here", "Hair", "Heir", "Hire"], a: 0 },
        { q: "Which is a proper noun?", o: ["Country", "India", "Mountain", "River"], a: 1 },
        { q: "The plural of 'Sheep' is...?", o: ["Sheeps", "Sheep", "Sheepses", "Lambs"], a: 1 },
        { q: "Choose the correct spelling:", o: ["Believe", "Beleive", "Belive", "Bellieve"], a: 0 },
        { q: "What is the synonym of 'Quick'?", o: ["Slow", "Fast", "Lazy", "Quiet"], a: 1 },
        { q: "I ___ a student.", o: ["is", "am", "are", "be"], a: 1 },
        { q: "Which is a silent letter in 'Knowledge'?", o: ["K", "N", "O", "L"], a: 0 },
        { q: "The sun ___ in the East.", o: ["rise", "rises", "rising", "rose"], a: 1 },
        { q: "What is the antonym of 'Artificial'?", o: ["Natural", "Fake", "Modern", "Plastic"], a: 0 },
        { q: "Which word is a verb?", o: ["Action", "Act", "Active", "Actively"], a: 1 },
        { q: "What do you call a person who speaks two languages?", o: ["Monolingual", "Bilingual", "Trilingual", "Polyglot"], a: 1 },
        { q: "Which mark is used at the end of a question?", o: [".", "!", "?", ","], a: 2 },
        { q: "Complete: 'Better late than ___.'", o: ["early", "never", "now", "soon"], a: 1 }
    ],
    maths: [
        { q: "What is the value of 2^5?", o: ["10", "25", "32", "64"], a: 2 },
        { q: "What is the square root of 225?", o: ["12", "15", "20", "25"], a: 1 },
        { q: "Solve: 12 + 4 * 3", o: ["48", "24", "36", "16"], a: 1 },
        { q: "How many degrees are in a right angle?", o: ["45", "90", "180", "360"], a: 1 },
        { q: "Which is the smallest prime number?", o: ["0", "1", "2", "3"], a: 2 },
        { q: "Find the median of: 2, 4, 6, 8, 10", o: ["4", "5", "6", "8"], a: 2 },
        { q: "What is 15% of 200?", o: ["15", "30", "45", "60"], a: 1 },
        { q: "How many sides does a hexagon have?", o: ["5", "6", "7", "8"], a: 1 },
        { q: "The area of a rectangle is 50, length is 10. Width is...?", o: ["5", "40", "15", "500"], a: 0 },
        { q: "What is the value of Pi (approx)?", o: ["2.14", "3.14", "4.14", "5.14"], a: 1 },
        { q: "What is 100 divided by 0.5?", o: ["50", "150", "200", "250"], a: 2 },
        { q: "Sum of angles in a triangle?", o: ["90", "180", "270", "360"], a: 1 },
        { q: "Which is a perfect square?", o: ["2", "8", "27", "49"], a: 3 },
        { q: "The next number in sequence: 2, 4, 8, 16, ___", o: ["20", "24", "30", "32"], a: 3 },
        { q: "Convert 1/4 to percentage:", o: ["25%", "40%", "50%", "10%"], a: 0 },
        { q: "What is 7 * 8?", o: ["54", "56", "58", "60"], a: 1 },
        { q: "An isosceles triangle has how many equal sides?", o: ["0", "1", "2", "3"], a: 2 },
        { q: "What is the value of 0! (Zero Factorial)?", o: ["0", "1", "Undefined", "Infinite"], a: 1 },
        { q: "The diameter of a circle is 14. Radius is...?", o: ["7", "14", "21", "28"], a: 0 },
        { q: "Solve: 5x = 25. x is...?", o: ["2", "5", "10", "125"], a: 1 },
        { q: "How many minutes in 2.5 hours?", o: ["120", "150", "180", "200"], a: 1 },
        { q: "Which is the largest? 1/2, 1/3, 1/4, 1/5", o: ["1/2", "1/3", "1/4", "1/5"], a: 0 },
        { q: "What is 9 squared?", o: ["18", "72", "81", "99"], a: 2 },
        { q: "Value of Log 10 (Base 10)?", o: ["0", "1", "10", "100"], a: 1 },
        { q: "Number of prime numbers between 1 and 10?", o: ["3", "4", "5", "6"], a: 1 },
        { q: "What is 1000 - 455?", o: ["545", "555", "645", "655"], a: 0 },
        { q: "The perimeter of a square with side 5 is...?", o: ["10", "20", "25", "30"], a: 1 },
        { q: "What is the cube of 3?", o: ["9", "18", "27", "30"], a: 2 },
        { q: "A century has how many years?", o: ["10", "50", "100", "1000"], a: 2 },
        { q: "The symbol '>' means...?", o: ["Less than", "Equal to", "Greater than", "Not equal"], a: 2 },
        { q: "What is 1/2 + 1/2?", o: ["1/4", "1", "2/2", "0.5"], a: 1 },
        { q: "What is 3 * (4 + 5)?", o: ["17", "27", "12", "9"], a: 1 },
        { q: "How many zeros in one million?", o: ["4", "5", "6", "7"], a: 2 },
        { q: "Which is an even number?", o: ["3", "7", "12", "15"], a: 2 },
        { q: "The complement of a 30-degree angle is...?", o: ["60", "90", "150", "180"], a: 0 },
        { q: "The average of 10, 20, 30 is...?", o: ["10", "15", "20", "25"], a: 2 },
        { q: "What is the Roman numeral for 50?", o: ["X", "L", "C", "D"], a: 1 },
        { q: "Which is the smallest 3-digit number?", o: ["100", "111", "999", "101"], a: 0 },
        { q: "A millennium is how many years?", o: ["100", "500", "1000", "10000"], a: 2 },
        { q: "How many vertices in a cube?", o: ["4", "6", "8", "12"], a: 2 },
        { q: "Solve: x/2 = 10. x is...?", o: ["5", "10", "15", "20"], a: 3 },
        { q: "What is 11 * 11?", o: ["111", "121", "131", "141"], a: 1 },
        { q: "Which is not a polygon?", o: ["Circle", "Triangle", "Square", "Hexagon"], a: 0 },
        { q: "The distance around a circle is called...?", o: ["Radius", "Diameter", "Circumference", "Area"], a: 2 },
        { q: "A right triangle's hypotenuse rule is named after...?", o: ["Newton", "Pythagoras", "Einstein", "Euclid"], a: 1 },
        { q: "What is 80% of 50?", o: ["30", "40", "45", "50"], a: 1 },
        { q: "The sum of 1 to 10 is...?", o: ["45", "50", "55", "60"], a: 2 },
        { q: "A leap year has how many days?", o: ["364", "365", "366", "367"], a: 2 },
        { q: "Which is a prime number?", o: ["9", "15", "17", "21"], a: 2 },
        { q: "The product of 0 and any number is...?", o: ["1", "0", "The number", "Infinite"], a: 1 }
    ],
    physics: [
        { q: "What is the unit of Force?", o: ["Joule", "Watt", "Newton", "Pascal"], a: 2 },
        { q: "What is the speed of light?", o: ["3x10^5 m/s", "3x10^8 m/s", "3x10^6 m/s", "3x10^10 m/s"], a: 1 },
        { q: "Who discovered Gravity?", o: ["Einstein", "Newton", "Galileo", "Bohr"], a: 1 },
        { q: "What is the unit of Resistance?", o: ["Ampere", "Volt", "Ohm", "Farad"], a: 2 },
        { q: "Which instrument measures atmospheric pressure?", o: ["Thermometer", "Barometer", "Voltmeter", "Ammeter"], a: 1 },
        { q: "The boiling point of water in Celsius is...?", o: ["0", "50", "100", "212"], a: 2 },
        { q: "What is the smallest part of an element?", o: ["Molecule", "Atom", "Cell", "Proton"], a: 1 },
        { q: "Sound travels fastest in...?", o: ["Vacuum", "Air", "Water", "Steel"], a: 3 },
        { q: "Which color has the longest wavelength?", o: ["Blue", "Green", "Yellow", "Red"], a: 3 },
        { q: "What is the unit of Energy?", o: ["Joule", "Watt", "Newton", "Pascal"], a: 0 },
        { q: "Which mirror is used in car rearview mirrors?", o: ["Plane", "Concave", "Convex", "None"], a: 2 },
        { q: "The core of the sun produces energy by...?", o: ["Fission", "Fusion", "Combustion", "Radiation"], a: 1 },
        { q: "Which law states 'For every action there is an equal reaction'?", o: ["Newton's 1st", "Newton's 2nd", "Newton's 3rd", "Pascal's Law"], a: 2 },
        { q: "What is the charge of an electron?", o: ["Positive", "Negative", "Neutral", "None"], a: 1 },
        { q: "Which lens is used to correct Myopia?", o: ["Convex", "Concave", "Cylindrical", "Bifocal"], a: 1 },
        { q: "What is the value of 'g' on Earth?", o: ["8.8 m/s^2", "9.8 m/s^2", "10.8 m/s^2", "7.8 m/s^2"], a: 1 },
        { q: "A transformer works on the principle of...?", o: ["Self Induction", "Mutual Induction", "Conduction", "Eddy currents"], a: 1 },
        { q: "Which state of matter has no fixed shape or volume?", o: ["Solid", "Liquid", "Gas", "Plasma"], a: 2 },
        { q: "What is the frequency of human hearing (range)?", o: ["2Hz-200Hz", "20Hz-20,000Hz", "1Hz-1,000Hz", "10k-1M Hz"], a: 1 },
        { q: "Which planet is known as the Red Planet?", o: ["Venus", "Mars", "Jupiter", "Saturn"], a: 1 },
        { q: "What is the unit of Power?", o: ["Watt", "Joule", "Henry", "Tesla"], a: 0 },
        { q: "Absolute zero temperature in Kelvin is...?", o: ["273K", "0K", "-273K", "100K"], a: 1 },
        { q: "Light is a...?", o: ["Transverse wave", "Longitudinal wave", "Mechanical wave", "Sound wave"], a: 0 },
        { q: "Which device converts mechanical energy into electrical?", o: ["Motor", "Dynamo/Generator", "Battery", "Switch"], a: 1 },
        { q: "What is the unit of Frequency?", o: ["Watt", "Hertz", "Second", "Meter"], a: 1 },
        { q: "Who proposed the Theory of Relativity?", o: ["Newton", "Einstein", "Hawking", "Curie"], a: 1 },
        { q: "Density is equal to...?", o: ["Mass/Volume", "Volume/Mass", "Mass*Volume", "Mass+Volume"], a: 0 },
        { q: "What part of the eye controls light entry?", o: ["Retina", "Iris", "Lens", "Cornea"], a: 1 },
        { q: "A primary cell is a...?", o: ["Rechargeable", "Non-rechargeable", "Large battery", "Solar cell"], a: 1 },
        { q: "Escape velocity from Earth is approx...?", o: ["5 km/s", "11.2 km/s", "20 km/s", "3x10^8 m/s"], a: 1 },
        { q: "Which instrument measures current?", o: ["Voltmeter", "Ammeter", "Galvanometer", "Ohmmeter"], a: 1 },
        { q: "Kinetic energy formula is...?", o: ["mgh", "1/2 mv^2", "ma", "F*d"], a: 1 },
        { q: "The study of light is called...?", o: ["Acoustics", "Optics", "Thermodynamics", "Mechanics"], a: 1 },
        { q: "What is the unit of Capacitance?", o: ["Henry", "Farad", "Coulomb", "Ohm"], a: 1 },
        { q: "Which radioactive gas is found in homes?", o: ["Oxygen", "Radon", "Neon", "Argon"], a: 1 },
        { q: "The SI unit of magnetic field is...?", o: ["Tesla", "Gauss", "Weber", "Oersted"], a: 0 },
        { q: "Rainbow is caused by...?", o: ["Reflection", "Refraction", "Dispersion", "All of these"], a: 3 },
        { q: "Which material is used in solar cells?", o: ["Iron", "Copper", "Silicon", "Aluminum"], a: 2 },
        { q: "Work done is zero if...?", o: ["Force is zero", "Displacement is zero", "Angle is 90 deg", "All of these"], a: 3 },
        { q: "What is the unit of Luminous Intensity?", o: ["Lumen", "Candela", "Lux", "Watt"], a: 1 },
        { q: "A fuse wire should have...?", o: ["High resistance", "Low melting point", "High melting point", "Low conductivity"], a: 1 },
        { q: "Semiconductors have ___ conductivity than conductors.", o: ["More", "Less", "Equal", "Zero"], a: 1 },
        { q: "Which ray has the highest penetrating power?", o: ["Alpha", "Beta", "Gamma", "X-ray"], a: 2 },
        { q: "The time period of a simple pendulum depends on...?", o: ["Mass", "Length", "Amplitude", "Color"], a: 1 },
        { q: "Which law explains how airplanes fly?", o: ["Pascal's", "Bernoulli's", "Boyle's", "Hooke's"], a: 1 },
        { q: "Force = Mass * ...?", o: ["Velocity", "Acceleration", "Time", "Distance"], a: 1 },
        { q: "What is the refractive index of vacuum?", o: ["0", "1", "1.33", "2.42"], a: 1 },
        { q: "Which force holds planets in orbit?", o: ["Magnetic", "Gravitational", "Frictional", "Elastic"], a: 1 },
        { q: "Potential energy formula is...?", o: ["1/2 mv^2", "ma", "mgh", "Force/Area"], a: 2 },
        { q: "Atomic number is the number of...?", o: ["Neutrons", "Electrons", "Protons", "Nucleons"], a: 2 }
    ],
    chemistry: [
        { q: "What is the chemical symbol for Gold?", o: ["Go", "Gd", "Au", "Ag"], a: 2 },
        { q: "Which gas is known as Laughing Gas?", o: ["Nitrous Oxide", "Carbon Dioxide", "Methane", "Oxygen"], a: 0 },
        { q: "What is the pH value of pure water?", o: ["0", "5", "7", "14"], a: 2 },
        { q: "Which element is the most abundant in Earth's atmosphere?", o: ["Oxygen", "Hydrogen", "Nitrogen", "Carbon"], a: 2 },
        { q: "The chemical formula for Common Salt is...?", o: ["KCl", "NaCl", "NaOH", "HCl"], a: 1 },
        { q: "Which metal is kept in kerosene?", o: ["Sodium", "Iron", "Gold", "Silver"], a: 0 },
        { q: "What is the hardest natural substance?", o: ["Gold", "Iron", "Diamond", "Graphite"], a: 2 },
        { q: "Which gas is used in soda water?", o: ["Oxygen", "Hydrogen", "Carbon Dioxide", "Nitrogen"], a: 2 },
        { q: "Atomic number of Carbon is...?", o: ["4", "6", "12", "14"], a: 1 },
        { q: "Rusting of iron is a...?", o: ["Physical change", "Chemical change", "Biological change", "None"], a: 1 },
        { q: "Which gas do plants absorb during photosynthesis?", o: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], a: 1 },
        { q: "The chemical name for Baking Soda is...?", o: ["Sodium Carbonate", "Sodium Bicarbonate", "Calcium Carbonate", "Potassium Nitrate"], a: 1 },
        { q: "Which acid is present in lemons?", o: ["Acetic Acid", "Citric Acid", "Lactic Acid", "Hydrochloric Acid"], a: 1 },
        { q: "What is the lightest element?", o: ["Oxygen", "Helium", "Hydrogen", "Lithium"], a: 2 },
        { q: "The chemical symbol for Mercury is...?", o: ["Me", "Hg", "Hy", "Mg"], a: 1 },
        { q: "What is the main component of LPG?", o: ["Methane", "Ethane", "Butane", "Propane"], a: 2 },
        { q: "Which acid is found in the human stomach?", o: ["HCl", "H2SO4", "HNO3", "Citric"], a: 0 },
        { q: "What is the common name for Calcium Carbonate?", o: ["Salt", "Sugar", "Chalk/Marble", "Sand"], a: 2 },
        { q: "Which element is common to all acids?", o: ["Oxygen", "Hydrogen", "Nitrogen", "Chlorine"], a: 1 },
        { q: "Galvanization is the coating of...?", o: ["Lead", "Tin", "Zinc", "Copper"], a: 2 },
        { q: "Which gas is used for ripening fruits?", o: ["Ethylene", "Methane", "Ethane", "Oxygen"], a: 0 },
        { q: "What is dry ice?", o: ["Solid Oxygen", "Solid CO2", "Liquid Nitrogen", "Cold Water"], a: 1 },
        { q: "Which non-metal is a good conductor of electricity?", o: ["Iodine", "Graphite", "Sulfur", "Phosphorus"], a: 1 },
        { q: "Symbol for Iron is...?", o: ["Ir", "Fe", "In", "Io"], a: 1 },
        { q: "Study of carbon compounds is called...?", o: ["Inorganic", "Organic", "Physical", "Analytical"], a: 1 },
        { q: "The valency of Oxygen is...?", o: ["1", "2", "3", "4"], a: 1 },
        { q: "Which gas is used in electric bulbs?", o: ["Oxygen", "Hydrogen", "Argon/Nitrogen", "Carbon Dioxide"], a: 2 },
        { q: "Acid turns blue litmus paper into...?", o: ["Green", "Yellow", "Red", "Colorless"], a: 2 },
        { q: "Which metal is the best conductor of electricity?", o: ["Copper", "Silver", "Gold", "Aluminum"], a: 1 },
        { q: "What is the molecular formula of water?", o: ["HO", "H2O", "H2O2", "HO2"], a: 1 },
        { q: "Mendeleev is famous for creating the...?", o: ["Laws of Motion", "Periodic Table", "Relativity", "Microscope"], a: 1 },
        { q: "Which element is used in pencils?", o: ["Lead", "Graphite", "Charcoal", "Coal"], a: 1 },
        { q: "A neutral solution has a pH of...?", o: ["0", "7", "14", "1"], a: 1 },
        { q: "Brass is an alloy of...?", o: ["Copper/Tin", "Copper/Zinc", "Iron/Carbon", "Zinc/Lead"], a: 1 },
        { q: "What is the atomic number of Hydrogen?", o: ["0", "1", "2", "1.1"], a: 1 },
        { q: "The process of converting liquid to gas is...?", o: ["Melting", "Freezing", "Evaporation", "Condensation"], a: 2 },
        { q: "Which gas is used in the treatment of water?", o: ["Fluorine", "Chlorine", "Bromine", "Iodine"], a: 1 },
        { q: "Name the heaviest naturally occurring element?", o: ["Uranium", "Lead", "Gold", "Mercury"], a: 0 },
        { q: "Vitamin C is also known as...?", o: ["Citric acid", "Ascorbic acid", "Folic acid", "Acetic acid"], a: 1 },
        { q: "What is the main metal in Haemoglobin?", o: ["Calcium", "Magnesium", "Iron", "Zinc"], a: 2 },
        { q: "Synthetic fiber 'Rayon' is made from...?", o: ["Petroleum", "Wood Pulp", "Coal", "Natural Gas"], a: 1 },
        { q: "Which noble gas is most common in atmosphere?", o: ["Helium", "Neon", "Argon", "Xenon"], a: 2 },
        { q: "Water gas is a mixture of...?", o: ["CO + H2", "CO2 + H2", "CO + N2", "CH4 + H2"], a: 0 },
        { q: "Ozone layer protects us from...?", o: ["X-rays", "Gamma rays", "UV rays", "Infrared"], a: 2 },
        { q: "Which is the most reactive metal?", o: ["Potassium", "Sodium", "Calcium", "Magnesium"], a: 0 },
        { q: "What is the chemical name for Vinegar?", o: ["Formic acid", "Acetic acid", "Malic acid", "Tartaric acid"], a: 1 },
        { q: "Symbol for Potassium is...?", o: ["P", "Po", "K", "Ka"], a: 2 },
        { q: "How many periods are in the Modern Periodic Table?", o: ["7", "8", "18", "10"], a: 0 },
        { q: "Fire extinguishers contain...?", o: ["O2", "CO2", "N2", "H2"], a: 1 },
        { q: "Common name for Sodium Carbonate?", o: ["Baking Soda", "Washing Soda", "Caustic Soda", "Bleaching Powder"], a: 1 }
    ],
    cs: [
        { q: "What is the full form of CPU?", o: ["Computer Processing Unit", "Central Processing Unit", "Control Panel Unit", "Core Program Unit"], a: 1 },
        { q: "Which part is considered the 'Brain' of the computer?", o: ["RAM", "Monitor", "CPU", "Keyboard"], a: 2 },
        { q: "What is 1 Byte equal to?", o: ["4 bits", "8 bits", "16 bits", "1024 bits"], a: 1 },
        { q: "Which is a volatile memory?", o: ["ROM", "Hard Disk", "RAM", "CD-ROM"], a: 2 },
        { q: "What does WWW stand for?", o: ["Web World Wide", "World Wide Web", "World Whole Web", "Web Work World"], a: 1 },
        { q: "Who is known as the Father of Computers?", o: ["Bill Gates", "Charles Babbage", "Alan Turing", "Steve Jobs"], a: 1 },
        { q: "Which is an Output device?", o: ["Keyboard", "Mouse", "Scanner", "Monitor"], a: 3 },
        { q: "What is the binary base?", o: ["2", "8", "10", "16"], a: 0 },
        { q: "HTTP stands for...?", o: ["Hypertext Transfer Protocol", "High Text Transfer Protocol", "Hyper Tool Transfer", "None"], a: 0 },
        { q: "Which is an Operating System?", o: ["MS Word", "Google Chrome", "Linux", "Java"], a: 2 },
        { q: "One Kilobyte (KB) is equal to...?", o: ["1000 Bytes", "1024 Bytes", "1048 Bytes", "512 Bytes"], a: 1 },
        { q: "Which shortcut is used to Copy?", o: ["Ctrl+X", "Ctrl+V", "Ctrl+C", "Ctrl+A"], a: 2 },
        { q: "What is the full form of RAM?", o: ["Read Access Memory", "Random Access Memory", "Run Access Memory", "Real Access Memory"], a: 1 },
        { q: "Which is the smallest unit of data?", o: ["Bit", "Byte", "Nibble", "KB"], a: 0 },
        { q: "What does IP stand for?", o: ["Internal Protocol", "Internet Protocol", "Index Protocol", "Input Process"], a: 1 },
        { q: "Which device connects a computer to the internet?", o: ["Mouse", "Modem", "Printer", "Scanner"], a: 1 },
        { q: "What is a 'Bug' in software?", o: ["A virus", "An error", "A design feature", "A fast program"], a: 1 },
        { q: "Which language is used for web design styling?", o: ["HTML", "C++", "CSS", "Python"], a: 2 },
        { q: "What is the permanent memory of computer?", o: ["RAM", "ROM", "Cache", "Register"], a: 1 },
        { q: "Which is a Search Engine?", o: ["Facebook", "Google", "WhatsApp", "Spotify"], a: 1 },
        { q: "What is the full form of URL?", o: ["Uniform Resource Locator", "Universal Resource Link", "United Road Line", "None"], a: 0 },
        { q: "Which key is used to refresh a web page?", o: ["F1", "F2", "F5", "F10"], a: 2 },
        { q: "What does GUI stand for?", o: ["General User Interface", "Graphical User Interface", "Global User Index", "Group User Info"], a: 1 },
        { q: "Which is NOT a programming language?", o: ["Java", "Python", "C#", "MS Excel"], a: 3 },
        { q: "What is the main circuit board of computer?", o: ["Monitor", "CPU", "Motherboard", "Keyboard"], a: 2 },
        { q: "Which protocol is used for email?", o: ["HTTP", "FTP", "SMTP", "SNMP"], a: 2 },
        { q: "What is the full form of PDF?", o: ["Personal Data File", "Portable Document Format", "Printable Document File", "None"], a: 1 },
        { q: "Which is a High-Level Language?", o: ["Machine Code", "Assembly", "Java", "Binary"], a: 2 },
        { q: "A folder in computer is used to...?", o: ["Delete files", "Organize files", "Create internet", "Speed up PC"], a: 1 },
        { q: "What is the full form of USB?", o: ["Universal Serial Bus", "United Serial Binary", "Universal System Board", "None"], a: 0 },
        { q: "Which is a Cloud storage?", o: ["Hard Disk", "Google Drive", "RAM", "Flash Drive"], a: 1 },
        { q: "What is the extension of an Excel file?", o: [".docx", ".pptx", ".xlsx", ".txt"], a: 2 },
        { q: "Who co-founded Microsoft?", o: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Larry Page"], a: 1 },
        { q: "Which is the main language for AI today?", o: ["C", "COBOL", "Python", "Pascal"], a: 2 },
        { q: "What is 'phishing'?", o: ["Coding", "Fish game", "Cyber attack", "Software update"], a: 2 },
        { q: "Which is a Social Media platform?", o: ["Outlook", "Instagram", "Amazon", "Netflix"], a: 1 },
        { q: "What does BIOS stand for?", o: ["Binary Input OS", "Basic Input Output System", "Binary Info System", "None"], a: 1 },
        { q: "Which device is used for playing games?", o: ["Joystick", "Printer", "Scanner", "UPS"], a: 0 },
        { q: "What is the shortcut to Undo?", o: ["Ctrl+Y", "Ctrl+U", "Ctrl+Z", "Ctrl+X"], a: 2 },
        { q: "What does VPN stand for?", o: ["Virtual Private Network", "Visual Private Net", "Virtual Public Network", "None"], a: 0 },
        { q: "Which is a database software?", o: ["PowerPoint", "MySQL", "Notepad", "VLC"], a: 1 },
        { q: "What is the full form of LCD?", o: ["Light Crystal Display", "Liquid Crystal Display", "Liquid Color Display", "None"], a: 1 },
        { q: "Which is a wireless network tech?", o: ["Ethernet", "Wi-Fi", "USB", "HDMI"], a: 1 },
        { q: "What is the shortcut to save?", o: ["Ctrl+S", "Alt+S", "Shift+S", "Ctrl+P"], a: 0 },
        { q: "What is the default browser for Windows?", o: ["Chrome", "Safari", "Edge", "Firefox"], a: 2 },
        { q: "Which is a Mobile OS?", o: ["Windows 10", "Android", "macOS", "Linux"], a: 1 },
        { q: "What does LAN stand for?", o: ["Large Area Network", "Local Area Network", "Link Area Net", "None"], a: 1 },
        { q: "A group of computers connected together is a...?", o: ["Monitor", "Network", "Hardware", "Software"], a: 1 },
        { q: "Which language is used for Android apps?", o: ["Swift", "Kotlin/Java", "PHP", "Objective-C"], a: 1 },
        { q: "Who is the CEO of Google?", o: ["Sundar Pichai", "Satya Nadella", "Elon Musk", "Tim Cook"], a: 0 }
    ]
};
